### ISSUE TITLE
TypeError: Fetch argument None has invalid type <class 'NoneType'> 

### ISSUE THREAD

**Issue by marleymwangi** [adeshpande3/LSTM-Sentiment-Analysis#14]
Hi, first thing: your project is very interesting.
Second: I got an error at the execution at

summary = sess.run( merged , {input_data: nextBatch, labels: nextBatchLabels})

Do you have any ideas how to fix it ?

Thank you in advance

Traceback (most recent call last):
File "Oriole+LSTM.py", line 220, in 
summary = sess.run( merged , {input_data: nextBatch, labels: nextBatchLabels})
File "C:\Anaconda\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 789, in run
run_metadata_ptr)
File "C:\Anaconda\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 984, in _run
self._graph, fetches, feed_dict_string, feed_handles=feed_handles)
File "C:\Anaconda\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 410, in init
self._fetch_mapper = _FetchMapper.for_fetch(fetches)
File "C:\Anaconda\Anaconda3\envs\tensorflow\lib\site-packages\tensorflow\python\client\session.py", line 227, in for_fetch
(fetch, type(fetch)))
TypeError: Fetch argument None has invalid type <class 'NoneType'>

**Comment by adeshpande3** [comment]
It seems as though the merged variable doesn't have any value assigned to it. Do you want to upload your results to Tensorboard? That's the only reason you should be running that particular sess.run command. If you do want to upload, then you need to make sure that you've run the following code which defines merged. 

![image](https://user-images.githubusercontent.com/13543909/32870340-508c9aae-ca30-11e7-8ff2-0108a47362f0.png)

**Comment by marleymwangi** [comment]
Thanks a lot. Fixed my problem
