### ISSUE TITLE
Issue when running code 

### ISSUE THREAD

**Issue by rakesh903** [adeshpande3/LSTM-Sentiment-Analysis#24]
Hi,
I am getting error when I am trying to train the model. 

Below is the error.

Traceback (most recent call last):
  File "D:/Projects/ML/DeepL/NLPLSTM/lstm/lst.py", line 234, in <module>
    nextBatch, nextBatchLabels = getTrainBatch()
  File "D:/Projects/ML/DeepL/NLPLSTM/lstm/lst.py", line 170, in getTrainBatch
    arr[i] = ids[num-1:num]
ValueError: could not broadcast input array from shape (0,250) into shape (250)

Code:

def getTrainBatch():
    labels = []
    arr = np.zeros([batchSize, maxSeqLength])
    for i in range(batchSize):
        if i % 2 == 0:
            num = randint(1,11499)
            labels.append([1,0])
        else:
            num = randint(13499,24999)
            labels.append([0,1])
        arr[i] = ids[num-1:num]
    return arr, labels

**Comment by adelabdelli** [comment]
i got the same error, i don't know why !! are you using your own dataset ? if yes you have to change the randint value, i'd change and it works but after that i tried to re-run it but it give the same error

**Comment by adelabdelli** [comment]
@adeshpande3  please Help us

**Comment by rakesh903** [comment]
I did resolve it my self. 
The shape of the input needs to be changed. Use numpy to change the shape.

Thanks

**Comment by adelabdelli** [comment]
How to reshape it , i mean from what to what ?

**Comment by linjunouyang** [comment]
I'm not sure.

In getTrainBatch(), change from 
`arr[i] = ids[num-1:num]`
to
`arr[i] = ids[num-1]`

Is this correct???

**Comment by roaminggypsy** [comment]
I don't know how to solve this. 
Could you please explain your solution?

**Comment by adeshpande3** [comment]
If you're getting an error like "ValueError: could not broadcast input array from shape (0,250) into shape (250)", then that means your ids matrix may not be filled properly. Check to see that there are indeed values inside that matrix.

**Comment by roaminggypsy** [comment]
Thanks for your reply.

I solved this problem.
There are some typos in the `negativeFiles` initialization (so `negativeFiles` was empty) I fixed them.

Also,
In getTrainBatch():
`arr[i] = ids[num-1:num]`
I change to
`arr[i] = ids[num-1]`

**Comment by adeshpande3** [comment]
What were the typos?
